# Site settings
title: Enby Utopia
SEOTitle: Die Basisstation -- THE NONBINARY UTOPIA
header-img: img/home-bg-bluestars.jpg
email: enbyutopia@163.com
description: "The future is beyond the binary."
keyword: "Constructed Language, Ligua Franca, Interlingua, Globien"
url: "https://enbyutopia.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/enbyutopia/enbyutopia.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I am who I am because I follow my own path."
sidebar-avatar: /img/enby_utopia.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# weibo_username:     qiubaiying
# zhihu_username:       henry-jiang-78
github_username:      EnbyUtopia
wechat_id(Robot Xiao U):            qsbjdzs
wechat_id(Die Basisstation):        zhyymnyWljz
# facebook_username:    henry.h.jiang.5
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 6a11cab9f46fe57e56a1                            #生成的clientID
  clientSecret: 27ac9ec88d1ecd4c819f7423c95b4ca66e54156a    #生成的clientSecret
  repo:  enbyutopia.github.io    #仓库名称
  owner: enbyutopia    #github用户名
  admin: enbyutopia
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除
friends: [
    {
        title: "Enby Utopia",
        href: "https://enbyutopia.github.io"
    },{
        title: "Enby Community",
        href: "https://www.douban.com/group/735671/"
    },{
        title: "Twitter of A Volunteer",
        href: "https://twitter.com/uichizei"
    }
]
